name: CI
on: [push, pull_request]

jobs:
  bsd:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.0'
            host: ubuntu-latest
          - name: netbsd
            architecture: x86-64
            version: '10.0'
            host: ubuntu-latest
          - name: openbsd
            architecture: x86-64
            version: '7.4'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run CI script on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            # doas(1) isn't configured on OpenBSD.
            # See https://github.com/cross-platform-actions/action/issues/75
            sudo .github/workflows/prepare.sh
            .github/workflows/test.sh

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo .github/workflows/prepare.sh
      - name: Run tests
        run: |
          .github/workflows/test.sh

  mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          .github/workflows/prepare.sh
      - name: Run tests
        run: |
          .github/workflows/test.sh

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          .github/workflows/prepare.ps1
      - name: Run tests
        run: |
          .github/workflows/test.ps1
